### ISSUE TITLE
ERROR: deepspeech 0.9.1 has requirement numpy>=1.17.3, but you'll have numpy 1.16.6 which is incompatible.

### ISSUE THREAD

**Issue by prof-web-coding** [AIWintermuteAI/DeepSpeech_RaspberryPi4_Hotword#7]
Hi, I've cloned the project, run install.sh and I'm getting the following error:
`ERROR: deepspeech 0.9.1 has requirement numpy>=1.17.3, but you'll have numpy 1.16.6 which is incompatible.`
Then running it it does not work:
```
python3 mic_streaming.py --keywords blueberry
Initializing model...
INFO:root:Model: DeepSpeech_RaspberryPi4_Hotword/deepspeech-0.9.1-models.tflite
TensorFlow: v2.3.0-6-g23ad988
DeepSpeech: v0.9.1-0-gab8bd3e
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
2021-10-17 11:09:46.103991: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Data loss: Can't parse DeepSpeech_RaspberryPi4_Hotword/deepspeech-0.9.1-models.tflite as binary proto
Traceback (most recent call last):
  File "mic_streaming.py", line 272, in <module>
    main()
  File "mic_streaming.py", line 262, in main
    PorcupineDemo(
  File "mic_streaming.py", line 87, in __init__
    self.model = deepspeech.Model(model_name)
  File "/home/[]/.local/lib/python3.8/site-packages/deepspeech/__init__.py", line 38, in __init__
    raise RuntimeError("CreateModel failed with '{}' (0x{:X})".format(deepspeech.impl.ErrorCodeToErrorMessage(status),status))
RuntimeError: CreateModel failed with 'Error reading the proto buffer model file.' (0x3005)

```

**Comment by AIWintermuteAI** [comment]
Hi there!
It seems you are not running it on a Raspberry Pi. This repository is specifically made to be run on Raspberry Pi.
It might be possible for you to still run it if you replace 
https://github.com/AIWintermuteAI/DeepSpeech_RaspberryPi4_Hotword/blob/e58f76e505ac09feaa715b725441543228c1a55b/install.sh#L2
with 
```pip3 install deepspeech-tflite~=0.9.1```

It happens because on armhf platform pip3 install deepspeech installs the deepspeech-tflite package. But on arm64 system for example it install the regular deepspeech package which takes proto buffer model and not .tflite model.

**Comment by prof-web-coding** [comment]
Thanks a lot. Your explanation was very clear and you were 100% right. It runs out of the box on Raspberry Pi and in order to run it on linux the replacement in the install.sh file does the trick.
